### ISSUE TITLE
Scrollbars in editors causing hang

### ISSUE THREAD

**Issue by chrstphrchvz** [hotwolf/HSW12#10]
The terminal window appears to be adding the xscrollbar and removing it, preventing anything else from refreshing. I'll see if I can post a video of it.
Right now I'd think this is not an HSW12-specific bug: it might be a bug in the ["'real' need to scroll" logic](http://search.cpan.org/dist/Tk/pod/Scrolled.pod#OPTIONS) (the 'o' prefix used in the -scrollbars option in Perl/Tk's Scrolled constructor, so a potential workaround is to not use the 'o' prefix: [cf. hsw12_gui:1512](https://github.com/hotwolf/HSW12/blob/0388b62e60396cd811e855f5934f3f0a04535f44/Perl/hsw12_gui.pm#L1512)), but I need to confirm this on Linux to see if it isn't specific to XQuartz.

**Comment by hotwolf** [comment]
Hello Christopher,
I'd be interested to see a video or a screenshot of the phenomenon.  A also have no problem with enabling the scrollbars permanently, if the "o" option causes problems.
Thanks for finding and fixing the quirks in the HSW12 GUI.
Dirk

**Comment by chrstphrchvz** [comment]
I've confirmed this issue on Linux. It turns out selecting text is not a requirement; it's just a reliable way to trigger it. This can also be triggered using any editable text window such as the macro editor or the variables window editor: type Enter until the east scrollbar appears, then any character until there is no horizontal space remaining, at which point the issue should appear, where it alternates between showing and hiding the south scrollbar.

Here's a video of the issue in the variables window editor: https://youtu.be/JGtvEudOkKY
In that case I was able to use other UI elements, such as the Cancel button or even backspacing the text to the point that the issue went away, but unless I did so before clicking Cancel, the variables window editor could not be opened again, even though the rest of the UI may seem responsive (double clicking inside the variables window appears to do nothing: the perl process is still busy).

If I can separately confirm that the bug is from using -scrollbars => 'o…', then I may be able to open the issue upstream: https://rt.cpan.org/Public/Dist/Display.html?Name=Tk . I wonder if there's already a standard test widget to demonstrate this with, or another Perl/Tk program out there to try this on (I'm too young to have encountered any).

**Comment by hotwolf** [comment]
Hello Christopher,
Thanks for posting the video showing the oscillating scrollbars. 
Maybe we should enable all scrollbars permanently. I think the Tk framework has passed its peak. I'd be surprised if this bug would ever be fixed.
Dirk

**Comment by chrstphrchvz** [comment]
Thanks, Dirk.
Using the term "oscillation" I finally came across a thread on comp.lang.perl.tk where came across this issue over 10 years ago; even the current maintainer of Perl/Tk suggested the workaround of not using optional scrollbars, and seems it was never truly resolved or documented since then:
http://newsgroups.derkeiler.com/Archive/Comp/comp.lang.perl.tk/2005-12/threads.html#00110

The post describes the issue nearly the same way I would have: because the length of a Scrollbar (relative to the trough) for a Text or ROText widget is calculated using only the data currently in view, using optional scrollbars with Scrolled can end up alternating between two states: (1) a Scrollbar is needed to view all of the data (e.g. text on last line), so a Scrollbar is placed (2), but after placing the Scrollbar, the data that made the Scrollbar necessary is out of view, so it is assumed a Scrollbar is not needed, and it is removed (back to 1), placing the data back into view, and so on.

I will create a pull request shortly with the scrollbars permanently enabled.

**Comment by chrstphrchvz** [comment]
closed by #12
