### ISSUE TITLE
add mnemonic for NUL-terminated ASCII

### ISSUE THREAD

**Issue by chrstphrchvz** [hotwolf/HSW12#15]
I'm used to writing strings in S12 assembly using
```
    FCC "Hello, World!"
    DB  NUL
```
where `NUL EQU 0`. However, many assemblers for other platforms have a mnemonic for NUL-terminated strings, e.g. `.ASCIIZ`. Is there an existing mnemonic for Motorola platforms, or what would be an appropriate mnemonic, e.g. `FCZ` (similar to `FCC` and `FCS`), and would this be a good thing to add to HSW12ASM?

**Comment by hotwolf** [comment]
So far I've always used MSB-terminated strings in my applications (pseudo-opcode FCS), but it absolutely doesn't hurt to add another pseudo-opcode for zero-terminated strings. I like the mnemonic "FCZ" and implemented it in release 0.66.
