### ISSUE TITLE
Unplugging connected device freezes GUI

### ISSUE THREAD

**Issue by chrstphrchvz** [hotwolf/HSW12#6]
I try not to do this on purpose, but if a serial device gets unplugged for some reason while HSW12 was connected to it, e.g. `/dev/ttyUSB0` disappears, the GUI will no longer respond and the perl process goes into runaway CPU usage, even if the device is plugged back in/becomes available; the program has to then be closed/killed. This happens on both OS X and Linux. 
Preferably, HSW12 should warn that it can't access the device and not freeze, sort of like how `minicom` will say `Cannot open /dev/ttyUSB0!` and go back to normal operation if it's reconnected.
(HSW12 doesn't care if devices it's not connected to disappear, although the Port menu is generated when the program was launched and only shows devices that were present at the time.)

**Comment by hotwolf** [comment]
Thanks, I really appreciate all your feedback. At the moment I'm pretty much tied up in my other projects and I will probably not find the time to look into the GUI issues any time soon. 
Would you like to help me to improve the GUI code?

**Comment by chrstphrchvz** [comment]
That would be neat, although I'm not a developer (yet). I have Eclipse+EPIC and padwalker installed, but it seems I now need to figure out how to debug modules…

I haven't tried this, but there's probably also a workaround that would involve creating a virtual serial port for HSW12 to connect to and then binding it to the hotplugging serial device e.g. using `socat`.

**Comment by hotwolf** [comment]
Great, welcome to the HSW12 project. Why don't you contact me through the email address listed in my profile. Then we can discuss how we can work on the GUI code together.

By the way, I just use a plain text editor to write my Perl code, but I'd be interested to see how EPIC is working for you.

**Comment by chrstphrchvz** [comment]
From watching the debugger loop, `DoOneEvent()` is repeatedly calling `parse_input_stream()`, and although it looks like it wants to print out `Error! Can't read from device…` (line 640), I'm guessing `MainLoop()` never gets a chance to do so.

I think the problem is that there isn't anything in the body of the read error handler (`if (! defined $bytes)…`, hsw12_pod.pm:636) that causes the device to become undefined, as would be done by `set_device()` on line 437 (`$self->{device} = undef;`).

So my first guess for resolving this is to insert `$self->set_device(undef);` at line 647; now HSW12 prints
```
Error! Can't read from device "/dev/ttyUSB0" (Device not configured)
Error! Can't write to device "" (No such file or directory)
```
and no longer freezes.

This resolves the issue, but I'd like to confirm this is an appropriate solution--I'm not familiar enough with Perl/Tk (or any GUI tk for that matter) to know exactly what's going on. E.g., should only the existing error handler in `set_device()` (line 437) undefine the device?

**Comment by hotwolf** [comment]
Hello Christopher,

Sorry for not responding any sooner. 

What you are saying is, that if the USB device becomes unplugged, the file event is continuously called, as if read data was available. I didn’t know that.  What you are suggesting makes sense. "$self->set_device(undef)”  would close the “input_handle” and stop the the file event calls. The only thing is, that it doesn’t automatically reconnect, as soon as "/dev/ttyUSB0” is available again, but that’s ok.

I don’t have a chance to test your solution at the moment, but it sounds reasonable. And as long as it works for you, go ahead and push it to the repository.  Please let me know if you need any help with that.

Thanks for coming up with a fix for this freeze problem.

Dirk

**Comment by chrstphrchvz** [comment]
I finally created a pull request in case any changes (e.g. versioning) need to be made before merging.

Thanks,
Chris

**Comment by hotwolf** [comment]
Thanks for fixing the HSW12 GUI. I finally merged your changes into the main branch.
